import type { Metadata } from "next";
import { Open_Sans, Balsamiq_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared";

const openSans = Open_Sans({
  subsets: ["cyrillic"],
  variable: "--font-openSans",
  weight: ["400", "500", "600", "700", "800"],
});

const balsamiq = Balsamiq_Sans({
  subsets: ["cyrillic"],
  variable: "--font-openSans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Store sb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className}${balsamiq.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
